# Generated by Django 5.2.17 on 2026-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('analyst', 'Analista'), ('viewer', 'Visualizador')], default='viewer', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=10)),
                ('district_name', models.CharField(max_length=100)),
                ('no2_level', models.DecimalField(decimal_places=2, help_text='µg/m³', max_digits=6)),
                ('pm10_level', models.DecimalField(decimal_places=2, help_text='µg/m³', max_digits=6)),
                ('period_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Calidad del aire',
                'verbose_name_plural': 'Calidad del aire',
                'db_table': 'air_quality',
                'ordering': ['-period_date'],
                'indexes': [models.Index(fields=['district_code', 'period_date'], name='air_quality_distric_3199f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TourismPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=10)),
                ('district_name', models.CharField(max_length=100)),
                ('hut_count', models.IntegerField(help_text='Número de viviendas de uso turístico (HUT)')),
                ('avg_noise_db', models.DecimalField(decimal_places=2, help_text='Nivel acústico en dB', max_digits=5)),
                ('period_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Presión turística',
                'verbose_name_plural': 'Presión turística',
                'db_table': 'tourism_pressure',
                'ordering': ['-period_date'],
                'indexes': [models.Index(fields=['district_code', 'period_date'], name='tourism_pre_distric_983a6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=10)),
                ('district_name', models.CharField(max_length=100)),
                ('consumption_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Consumo de agua',
                'verbose_name_plural': 'Consumos de agua',
                'db_table': 'water_consumption',
                'ordering': ['-period_date'],
                'indexes': [models.Index(fields=['district_code', 'period_date'], name='water_consu_distric_2cd2a1_idx')],
            },
        ),
    ]
